DROP TABLE IF EXISTS `cbg_overlijden`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cbg_overlijden` (
	`id` int(11) unsigned NOT NULL,

	`Overledene_voornaam`                 VARCHAR( 100) DEFAULT NULL,
	`Overledene_patroniem`                VARCHAR( 100) DEFAULT NULL,
	`Overledene_tussenvoegsel`            VARCHAR(  30) DEFAULT NULL,
	`Overledene_achternaam`               VARCHAR( 100) DEFAULT NULL,
	`Overledene_geslacht`                 VARCHAR(  15) DEFAULT NULL,
	`Overledene_woonadres`                VARCHAR(  120) DEFAULT NULL,
	
	`Overledene_leeftijd_literal`         VARCHAR( 300) DEFAULT NULL,
	`Overledene_leeftijd_Jaar`            VARCHAR(  10) DEFAULT NULL,
	`Overledene_datum_geboorte_literal`   VARCHAR( 300) DEFAULT NULL,
	`Overledene_datum_geboorte_YYYY`      VARCHAR(  50) DEFAULT NULL,
	`Overledene_datum_geboorte_MM`        VARCHAR(  50) DEFAULT NULL,
	`Overledene_datum_geboorte_DD`        VARCHAR(  50) DEFAULT NULL,
	
	`Overledene_geboorteplaats`           VARCHAR( 120) DEFAULT NULL,
	`Overledene_beroep1`                  VARCHAR( 200) DEFAULT NULL,
	`Overledene_beroep2`                  VARCHAR( 200) DEFAULT NULL,
	`Overledene_relatie`                  VARCHAR(   0) DEFAULT NULL,
	
	`Vader_voornaam`                      VARCHAR( 100) DEFAULT NULL,
	`Vader_patroniem`                     VARCHAR( 100) DEFAULT NULL,
	`Vader_tussenvoegsel`                 VARCHAR(  30) DEFAULT NULL,
	`Vader_achternaam`                    VARCHAR( 100) DEFAULT NULL,
	`Vader_beroep1`                       VARCHAR( 200) DEFAULT NULL,
	`Vader_beroep2`                       VARCHAR( 200) DEFAULT NULL,
	
	`Moeder_voornaam`                     VARCHAR( 100) DEFAULT NULL,
	`Moeder_patroniem`                    VARCHAR( 100) DEFAULT NULL,
	`Moeder_tussenvoegsel`                VARCHAR(  30) DEFAULT NULL,
	`Moeder_achternaam`                   VARCHAR( 100) DEFAULT NULL,
	`Moeder_beroep1`                      VARCHAR( 200) DEFAULT NULL,
	`Moeder_beroep2`                      VARCHAR( 200) DEFAULT NULL,
	
	`Relatie1_voornaam`                   VARCHAR( 100) DEFAULT NULL,
	`Relatie1_patroniem`                  VARCHAR( 100) DEFAULT NULL,
	`Relatie1_tussenvoegsel`              VARCHAR(  30) DEFAULT NULL,
	`Relatie1_achternaam`                 VARCHAR( 100) DEFAULT NULL,
	`Relatie1_geslacht`                   VARCHAR(  15) DEFAULT NULL,
	`Relatie1_beroep1`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie1_beroep2`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie1_type`                       VARCHAR(  50) DEFAULT NULL,
	
	`Relatie2_voornaam`                   VARCHAR( 100) DEFAULT NULL,
	`Relatie2_patroniem`                  VARCHAR( 100) DEFAULT NULL,
	`Relatie2_tussenvoegsel`              VARCHAR(  30) DEFAULT NULL,
	`Relatie2_achternaam`                 VARCHAR( 100) DEFAULT NULL,
	`Relatie2_geslacht`                   VARCHAR(  15) DEFAULT NULL,
	`Relatie2_beroep1`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie2_beroep2`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie2_type`                       VARCHAR(  50) DEFAULT NULL,
	
	`Relatie3_voornaam`                   VARCHAR( 100) DEFAULT NULL,
	`Relatie3_patroniem`                  VARCHAR( 100) DEFAULT NULL,
	`Relatie3_tussenvoegsel`              VARCHAR(  30) DEFAULT NULL,
	`Relatie3_achternaam`                 VARCHAR( 100) DEFAULT NULL,
	`Relatie3_geslacht`                   VARCHAR(  15) DEFAULT NULL,
	`Relatie3_beroep1`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie3_beroep2`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie3_type`                       VARCHAR(  50) DEFAULT NULL,
	
	`Relatie4_voornaam`                   VARCHAR( 100) DEFAULT NULL,
	`Relatie4_patroniem`                  VARCHAR( 100) DEFAULT NULL,
	`Relatie4_tussenvoegsel`              VARCHAR(  30) DEFAULT NULL,
	`Relatie4_achternaam`                 VARCHAR( 100) DEFAULT NULL,
	`Relatie4_geslacht`                   VARCHAR(  15) DEFAULT NULL,
	`Relatie4_beroep1`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie4_beroep2`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie4_type`                       VARCHAR(  50) DEFAULT NULL,
	
	`Relatie5_voornaam`                   VARCHAR( 100) DEFAULT NULL,
	`Relatie5_patroniem`                  VARCHAR( 100) DEFAULT NULL,
	`Relatie5_tussenvoegsel`              VARCHAR(  30) DEFAULT NULL,
	`Relatie5_achternaam`                 VARCHAR( 100) DEFAULT NULL,
	`Relatie5_geslacht`                   VARCHAR(  15) DEFAULT NULL,
	`Relatie5_beroep1`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie5_beroep2`                    VARCHAR( 200) DEFAULT NULL,
	`Relatie5_type`                       VARCHAR(  50) DEFAULT NULL,
	
	`Overledene_datum_overlijden_literal` VARCHAR( 300) DEFAULT NULL,
	`Overledene_datum_overlijden_YYYY`    VARCHAR(  50) DEFAULT NULL,
	`Overledene_datum_overlijden_MM`      VARCHAR(  50) DEFAULT NULL,
	`Overledene_datum_overlijden_DD`      VARCHAR(  50) DEFAULT NULL,
	
	`Overledene_plaats_overlijden`        VARCHAR( 120) DEFAULT NULL,
	
	`Gemeentenaam`                        VARCHAR( 100) DEFAULT NULL,
	
	`Akte_datum_literal`                  VARCHAR( 300) DEFAULT NULL,
	`Akte_datum_YYYY`                     VARCHAR(  50) DEFAULT NULL,
	`Akte_datum_MM`                       VARCHAR(  50) DEFAULT NULL,
	`Akte_datum_DD`                       VARCHAR(  50) DEFAULT NULL,
	
	`Bronsoort`                           VARCHAR(  50) DEFAULT NULL,
	`Plaats_instelling`                   VARCHAR( 120) DEFAULT NULL,
	`Naam_instelling`                     VARCHAR( 100) DEFAULT NULL,
	`Toegangsnummer`                      VARCHAR(  20) DEFAULT NULL,
	`Inventarisnummer`                    VARCHAR(  10) DEFAULT NULL,
	`Aktenummer`                          VARCHAR(  30) DEFAULT NULL,
	
	`Scan_nummer_1`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_1`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_2`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_2`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_3`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_3`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_4`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_4`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_5`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_5`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_6`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_6`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_7`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_7`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_8`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_8`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_9`                       VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_9`                          VARCHAR( 200) DEFAULT NULL,
	`Scan_nummer_10`                      VARCHAR(  50) DEFAULT NULL,
	`Scan_uri_10`                         VARCHAR( 200) DEFAULT NULL,
	
	`Mutatiedatum`                        VARCHAR(  50) DEFAULT NULL,
	`Scan_URI_Origineel`                  VARCHAR( 200) DEFAULT NULL,
	`RecordGUID`                          VARCHAR(  80) DEFAULT NULL,
	`Opmerking`                           VARCHAR(2048) DEFAULT NULL,
	`AkteSoort`                           VARCHAR( 200) DEFAULT NULL,
	
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
