#!/bin/sh

# Python

# FL-13-Sep-2016

export PYTHON_LOCAL=/data/opt/Python/python-3.5.2

alias python=$PYTHON_LOCAL/bin/python3.5

export PYTHON_SITEPACKS=$PYTHON_LOCAL/lib/python3.5/site-packages

export PYTHONPATH=$PYTHON_SITEPACKS

# do not append ${PATH} to avoid mixing python versions
# you already have created an enviroment variable PATH_AT_LOGIN
export PATH=$PYTHON_LOCAL/bin:${PATH_AT_LOGIN}

export LD_LIBRARY_PATH=$PYTHON_LOCAL/lib

# [eof]
