-- Query 4

ALTER IGNORE TABLE <DBPREFIX>analyse_type_rollen
CHANGE COLUMN `ATY_ID` `ATY_ID` DECIMAL(12) NULL DEFAULT NULL ,
CHANGE COLUMN `VOLG_NR` `VOLG_NR` DECIMAL(12) NULL DEFAULT NULL ,
CHANGE COLUMN `ROL_ID` `ROL_ID` DECIMAL(12) NULL DEFAULT NULL ;