package worddistancer;

import java.io.*;
import javax.swing.JFileChooser;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.SingleFrameApplication;


/**
 * The application's main frame.
 */
public class WordDistancerView extends FrameView {

    public WordDistancerView(SingleFrameApplication app) {
        super(app);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taList1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taList2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taStatus = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bOpenList2 = new javax.swing.JButton();
        bOpenList1 = new javax.swing.JButton();
        tOutput = new javax.swing.JTextField();
        bOpenOutput = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbSame = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbAlgorithm = new javax.swing.JComboBox();
        bStart = new javax.swing.JButton();
        cbMaxDistance = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbRules = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbMinLength = new javax.swing.JComboBox();
        bTrimList1 = new javax.swing.JButton();
        bTrimList2 = new javax.swing.JButton();

        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        taList1.setColumns(20);
        taList1.setRows(5);
        taList1.setName("taList1"); // NOI18N
        jScrollPane2.setViewportView(taList1);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        taList2.setColumns(20);
        taList2.setRows(5);
        taList2.setName("taList2"); // NOI18N
        jScrollPane3.setViewportView(taList2);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        taStatus.setColumns(20);
        taStatus.setRows(5);
        taStatus.setName("taStatus"); // NOI18N
        jScrollPane4.setViewportView(taStatus);

        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setName("jSeparator2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(worddistancer.WordDistancerApp.class).getContext().getResourceMap(WordDistancerView.class);
        bOpenList2.setText(resourceMap.getString("bOpenList2.text")); // NOI18N
        bOpenList2.setName("bOpenList2"); // NOI18N
        bOpenList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenList2ActionPerformed(evt);
            }
        });

        bOpenList1.setText(resourceMap.getString("bOpenList1.text")); // NOI18N
        bOpenList1.setName("bOpenList1"); // NOI18N
        bOpenList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenList1ActionPerformed(evt);
            }
        });

        tOutput.setText(resourceMap.getString("tOutput.text")); // NOI18N
        tOutput.setName("tOutput"); // NOI18N

        bOpenOutput.setText(resourceMap.getString("bOpenOutput.text")); // NOI18N
        bOpenOutput.setName("bOpenOutput"); // NOI18N
        bOpenOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenOutputActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cbSame.setText(resourceMap.getString("cbSame.text")); // NOI18N
        cbSame.setName("cbSame"); // NOI18N
        cbSame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSameActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        cbAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Levenshtein-Normal", "Levenshtein-TREE", "Levenshtein-TREE with VALUE" }));
        cbAlgorithm.setName("cbAlgorithm"); // NOI18N

        bStart.setText(resourceMap.getString("bStart.text")); // NOI18N
        bStart.setName("bStart"); // NOI18N
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        cbMaxDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbMaxDistance.setName("cbMaxDistance"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        cbRules.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Char 1 same", "Char 1/2 same", "Char 1/2/3 same", "Char 1/2/3/4 same", "Char 1/2/3/4/5 same", "Char 1 same (ijy/ck/sz)", "Char 1/2 same (ijy/ck/sz)", "Char 1/2/3 same (ijy/ck/sz)", "Char 1/2/3/4 same (ijy/ck/sz)", "Char 1/2/3/4/5 same (ijy/ck/sz)" }));
        cbRules.setName("cbRules"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        cbMinLength.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cbMinLength.setName("cbMinLength"); // NOI18N

        bTrimList1.setText(resourceMap.getString("bTrimList1.text")); // NOI18N
        bTrimList1.setName("bTrimList1"); // NOI18N
        bTrimList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrimList1ActionPerformed(evt);
            }
        });

        bTrimList2.setText(resourceMap.getString("bTrimList2.text")); // NOI18N
        bTrimList2.setName("bTrimList2"); // NOI18N
        bTrimList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrimList2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(bTrimList1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(bOpenList1)
                                .addGap(18, 18, 18)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(bTrimList2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(bOpenList2)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSame)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bStart, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(tOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bOpenOutput))
                                    .addComponent(cbRules, 0, 289, Short.MAX_VALUE)
                                    .addComponent(cbMaxDistance, 0, 289, Short.MAX_VALUE)
                                    .addComponent(cbAlgorithm, 0, 289, Short.MAX_VALUE)
                                    .addComponent(cbMinLength, 0, 289, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(bOpenOutput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMinLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMaxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(cbSame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(bStart))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bOpenList1)
                            .addComponent(bOpenList2)
                            .addComponent(bTrimList1)
                            .addComponent(bTrimList2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        LvTree lt = new LvTree( 
                taList1.getText().split("\\n"), 
                taList2.getText().split("\\n"), 
                taStatus, 
                cbMinLength.getSelectedItem().toString(), 
                cbMaxDistance.getSelectedItem().toString(), 
                tOutput.getText(), 
                cbAlgorithm.getSelectedIndex(),
                cbRules.getSelectedIndex());
        lt.start();
    }//GEN-LAST:event_bStartActionPerformed

    private void bOpenOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenOutputActionPerformed
       
        JFileChooser fileopen = new JFileChooser();

        int ret = fileopen.showDialog(null, "Choice a outpout file");

        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile(); 
            tOutput.setText( file.getPath() );
        }   
    }//GEN-LAST:event_bOpenOutputActionPerformed

    private void bOpenList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenList1ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileopen = new JFileChooser();

        int ret = fileopen.showDialog(null, "Open file");

        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
           // jTextArea3.setText(file.getPath());
            
            // now read
            
            String result = null;
        DataInputStream in = null;

        try {
            File f = new File(file.getPath());
            byte[] buffer = new byte[(int) f.length()];
            in = new DataInputStream(new FileInputStream(f));
            in.readFully(buffer);
            result = new String(buffer, "ISO-8859-1");
        } catch (IOException e) {
            throw new RuntimeException("IO problem in fileToString", e);
        } finally {
            try {
                in.close();
            } catch (IOException e) { /* ignore it */
            }
        }
            taList1.setText(result.replaceAll("\r", ""));
        }
    }//GEN-LAST:event_bOpenList1ActionPerformed

    private void bOpenList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenList2ActionPerformed
        
        JFileChooser fileopen = new JFileChooser();

        int ret = fileopen.showDialog(null, "Open file");

        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            String result = null;
            DataInputStream in = null;

        try {
            File f = new File(file.getPath());
            byte[] buffer = new byte[(int) f.length()];
            in = new DataInputStream(new FileInputStream(f));
            in.readFully(buffer);
            result = new String(buffer, "ISO-8859-1");
        } catch (IOException e) {
            throw new RuntimeException("IO problem in fileToString", e);
        } finally {
            try {
                in.close();
            } catch (IOException e) { /* ignore it */
            }
        }
            taList2.setText(result.replaceAll("\r", ""));
        }
        
    }//GEN-LAST:event_bOpenList2ActionPerformed

    private void cbSameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSameActionPerformed
        
        // Disable
        if(cbSame.isSelected()){
            taList2.setText(taList1.getText());
            taList2.setEnabled(false);
            bOpenList2.setEnabled(false);
            bTrimList2.setEnabled(false);
            return;
        }
        
        // Enable
        taList2.setEnabled(true);
        bOpenList2.setEnabled(true);
        bTrimList2.setEnabled(true);
        
    }//GEN-LAST:event_cbSameActionPerformed

    private void bTrimList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrimList1ActionPerformed
        
        String list = taList1.getText();
        
        String[] listArray = list.split("\n");
        
        for ( int i = 0 ; i < listArray.length ; i++ ) {
            listArray[i] = listArray[i].trim();
        }
        
        // Empty
        taList1.setText("");
        
        taList1.append( listArray[0] );
        
        for ( int i = 1 ; i < listArray.length ; i++ ) {
            taList1.append( "\n" + listArray[i] );
        }
        
        if(cbSame.isSelected()){
            taList2.setText(taList1.getText());
        }
    }//GEN-LAST:event_bTrimList1ActionPerformed

    private void bTrimList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrimList2ActionPerformed
        
        String list = taList2.getText();
        
        String[] listArray = list.split("\n");
        
        for ( int i = 0 ; i < listArray.length ; i++ ) {
            listArray[i] = listArray[i].trim();
        }
        
        // Empty
        taList2.setText("");
        
        taList2.append( listArray[0] );
        
        for ( int i = 1 ; i < listArray.length ; i++ ) {
            taList2.append( "\n" + listArray[i] );
        }
    }//GEN-LAST:event_bTrimList2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOpenList1;
    private javax.swing.JButton bOpenList2;
    private javax.swing.JButton bOpenOutput;
    private javax.swing.JButton bStart;
    private javax.swing.JButton bTrimList1;
    private javax.swing.JButton bTrimList2;
    private javax.swing.JComboBox cbAlgorithm;
    private javax.swing.JComboBox cbMaxDistance;
    private javax.swing.JComboBox cbMinLength;
    private javax.swing.JComboBox cbRules;
    private javax.swing.JCheckBox cbSame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tOutput;
    private javax.swing.JTextArea taList1;
    private javax.swing.JTextArea taList2;
    private javax.swing.JTextArea taStatus;
    // End of variables declaration//GEN-END:variables
}
